# Generated by Django 4.1.3 on 2022-12-13 17:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('date_of_birth', models.DateField(default=datetime.date.today, verbose_name='Дата рождения')),
                ('image', models.ImageField(upload_to='static/actors/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Актёры и режиссёры',
                'verbose_name_plural': 'Актёры и режиссёры',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.ImageField(upload_to='static/poster/', verbose_name='Постер')),
                ('banner', models.ImageField(upload_to='static/banner/', verbose_name='Банер')),
                ('video', models.FileField(default='cat.mp4', upload_to='static/video/')),
                ('year', models.PositiveSmallIntegerField(default=2022, verbose_name='Дата выхода')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('budget', models.PositiveSmallIntegerField(default=0, help_text='Сумма в долларах', verbose_name='Бюджет')),
                ('fees_in_usa', models.PositiveSmallIntegerField(default=0, help_text='Сумма в долларах', verbose_name='Сборы в США')),
                ('fees_in_world', models.PositiveSmallIntegerField(default=0, help_text='Сумма в долларах', verbose_name='Сборы в мире')),
                ('actors', models.ManyToManyField(related_name='film_actor', to='movies.actor', verbose_name='Актёры')),
                ('directors', models.ManyToManyField(related_name='film_director', to='movies.actor', verbose_name='Режиссёр')),
                ('genres', models.ManyToManyField(to='movies.genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=2000, verbose_name='Комментарий')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='фильм')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.reviews', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
