# Generated by Django 4.1.3 on 2022-12-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.FileField(default='1.mp4', upload_to='static/video/'),
        ),
    ]
