# Generated by Django 4.1.3 on 2022-12-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='format',
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(default='cat.mp4', upload_to='static/video/'),
        ),
    ]
