# Generated by Django 4.1.3 on 2022-12-13 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_reviews_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='parent',
        ),
    ]
