# Generated by Django 4.1.4 on 2022-12-19 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_reviews_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='promo',
            field=models.BooleanField(default=False, verbose_name='Промо'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='Фильм'),
        ),
    ]
